title: Olivier Denis
logo: profile.png
description: Paternity of Entropic Information Theory <br> Paternity of Holographic Gravity </br>
show_downloads: false
github: false
theme: jekyll-theme-minimal
